Update `xctest_runner` to fail if it doesn't execute any tests (#1133)
Ports https://github.com/bazelbuild/rules_apple/pull/1978 into
`rules_swift`.

- Updates the `xctest_runner` to fail if it doesn't execute any tests
- Adds tests for basic runner usage
- Adds tests for empty bundle cases

diff --git a/tools/xctest_runner/xctest_runner.sh.template b/tools/xctest_runner/xctest_runner.sh.template
--- a/tools/xctest_runner/xctest_runner.sh.template
+++ b/tools/xctest_runner/xctest_runner.sh.template
@@ -24,6 +24,7 @@ set -euo pipefail
 tmp_dir=$(mktemp -d)
 trap 'rm -rf "$tmp_dir"' EXIT
 readonly profraw="$tmp_dir/coverage.profraw"
+readonly testlog="$tmp_dir/test.log"
 
 # Foo.xctest/Contents/MacOS/Foo -> Foo.xctest
 executable_path="%executable%"
@@ -55,10 +56,19 @@ fi
 exit_status=0
 xctest=$(xcrun -f xctest)
 test_filter=${TESTBRIDGE_TEST_ONLY:-All}
-DYLD_INSERT_LIBRARIES=$sanitizer_dyld_env LLVM_PROFILE_FILE="$profraw" $xctest -XCTest "$test_filter" "$bundle_path" || exit_status=$?
+DYLD_INSERT_LIBRARIES=$sanitizer_dyld_env LLVM_PROFILE_FILE="$profraw" $xctest -XCTest "$test_filter" "$bundle_path" \
+  2>&1 | tee -i "$testlog" \
+  || exit_status=$?
 
 if [[ "$exit_status" -ne 0 ]]; then
   exit "$exit_status"
+fi
+
+# Fail when bundle executes nothing
+test_target_execution_count=$(grep -e "Executed [[:digit:]]\{1,\} tests*," "$testlog" | tail -n1)
+if echo "$test_target_execution_count" | grep -q -e "Executed 0 tests, with 0 failures"; then
+  echo "error: no tests were executed, is the test bundle empty?" >&2
+  exit 1
 fi
 
 if [[ "${COVERAGE:-}" -ne 1 ]]; then
